apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdf-manager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osdf-manager-app
  template:
    metadata:
      labels:
        app: osdf-manager-app
    spec:
      containers:
      - name: osdf-manager-app
        image: jhiemstra/osdf-flask-app
        volumeMounts:
          - name: maxmind-volume
            mountPath: /app/maxminddb
        ports:
        - containerPort: 8000
        env:
        - name: MAXMIND_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: maxmind-secret
              key: MaxMindKey
        - name: BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: condor-scitoken
              key: CondorToken
      volumes:
        - name: maxmind-volume
          persistentVolumeClaim:
            claimName: maxmind-pvc
      