apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maxmind-pvc
spec:
  storageClassName: 3x-replica-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 170Mi

