name: Build and push Docker image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'

env:
  DOCKER_IMAGE_NAME: Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
        password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./Dockerfile
        push: true
        tags: hub.opensciencegrid.org/${{ env.DOCKER_IMAGE_NAME }}:latest
