# name: Build and push Docker image

# on:
#   push:
#     branches:
#       - dev
#   pull_request:
#     branches:
#       - dev
#   schedule:
#     - cron: '0 7 * * *'

# env:
#   DOCKER_IMAGE_NAME: osdf-cache-man

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Login to Docker registry
#       uses: docker/login-action@v1
#       with:
#         registry: hub.opensciencegrid.org
#         username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
#         password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

#     - name: Build Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         dockerfile: ./Dockerfile
#         push: true
#         tags: hub.opensciencegrid.org/opensciencegrid/${{ env.DOCKER_IMAGE_NAME }}:latest.dev


name: Build and Push Docker Image Automatically

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  DOCKER_IMAGE_NAME: osdf-cache-director

jobs:

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'osg-htc/')

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Generate tag list
        id: generate-tag-list
        run: |
          if [ -z "${{ inputs.tag  }}" ]
          then 
            GITHUB_TAG=${GITHUB_REF##*/}
          else
            GITHUB_TAG=${{ inputs.tag }}
          fi
          
          echo "Master SHA:"
          echo $(git rev-parse $GITHUB_REF_NAME)
          
          echo "Current SHA:"
          echo $(git rev-parse HEAD)
          
          echo $GITHUB_TAG
          
          # # If this is a itb release lets tag it as such
          # if [[ $GITHUB_TAG == *"itb"* ]]; 
          # then
          #   ITB_SUFFIX="-itb"
          # else
          #   ITB_SUFFIX=""
          # fi
          
          tag_list=()
          for registry in hub.opensciencegrid.org; do
          #         "latest${ITB_SUFFIX}"
            for image_tag in "${GITHUB_TAG}" "$(git rev-parse HEAD)"; do
              tag_list+=("$registry"/opensciencegrid/"${{ env.DOCKER_IMAGE_NAME }}"":"$image_tag")
            done
          done
          # This causes the tag_list array to be comma-separated below,
          # which is required for build-push-action
          IFS=,
          echo "::set-output name=taglist::${tag_list[*]}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to OSG Harbor
        uses: docker/login-action@v1
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: "${{ steps.generate-tag-list.outputs.taglist }}"
