name: Build and Push Docker image

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - main
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

  build:
    runs-on: ubuntu-latest
    needs: [make-date-tag]
    strategy:
      fail-fast: False
    steps:
    - uses: actions/checkout@v2

    - name: Generate tag list
      id: generate-tag-list
      env:
        TIMESTAMP: ${{ needs.make-date-tag.outputs.dtag }}
      run: |
        if [ -z "${{ inputs.tag  }}" ]
        then
          echo ${GITHUB_REF##*/}
          if [[ ${GITHUB_REF##*/} =~ v[0-9]+\.[0-9]+\.[0-9]+ ]]
          then
            GITHUB_TAG=${GITHUB_REF##*/}
          else
            GITHUB_TAG="latest"
          fi
        else
          GITHUB_TAG=${{ inputs.tag }}
        fi

        echo "Master SHA:"
        echo $(git rev-parse $GITHUB_REF_NAME)
        
        echo "Current SHA:"
        echo $(git rev-parse HEAD)
        
        echo $GITHUB_TAG

        docker_repo="pelican_platform/director"
        tag_list=()
        for registry in hub.opensciencegrid.org; do
          if [ "$GITHUB_TAG" = "latest" ]
          then
            for image_tag in "$GITHUB_TAG" "$TIMESTAMP"; do
              tag_list+=("$registry/$docker_repo":"$image_tag")
            done
          else
            for image_tag in "$GITHUB_TAG"; do
              tag_list+=("$registry/$docker_repo":"$image_tag")
            done
          fi
        done
        # This causes the tag_list array to be comma-separated below,
        # which is required for build-push-action
        IFS=,
        echo "::set-output name=taglist::${tag_list[*]}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to OSG Harbor
      uses: docker/login-action@v1
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.PELICAN_HARBOR_ROBOT_USER }}
        password: ${{ secrets.PELICAN_HARBOR_ROBOT_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.0
      with:
        context: .
        push: true
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"
